apiVersion: {{ .Values.api.configmap | quote }}
kind: ConfigMap
metadata:
  name: {{ include "agent-sandbox.apiServiceConfigName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "agent-sandbox.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.config.apiService }}
  {{ $key }}: {{ tpl ($value | toString) $ | quote }}
{{- end }}
---
apiVersion: {{ .Values.api.configmap | quote }}
kind: ConfigMap
metadata:
  name: {{ include "agent-sandbox.runtimeGatewayConfigName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "agent-sandbox.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.config.runtimeGateway }}
  {{ $key }}: {{ tpl ($value | toString) $ | quote }}
{{- end }}
