{{- if .Values.serviceAccount.create }}
apiVersion: {{ .Values.api.serviceaccount | quote }}
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "agent-sandbox.labels" . | indent 4 }}
{{- end }}
{{- if .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "agent-sandbox.apiServiceName" . }}-runtime-gateway-discovery
  namespace: {{ .Values.namespace }}
  labels:
{{ include "agent-sandbox.labels" . | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      {{- if .Values.runtimeGateway.autoscaling.enabled }}
      - patch
      {{- end }}
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agent-sandbox.apiServiceName" . }}-runtime-gateway-discovery
  namespace: {{ .Values.namespace }}
  labels:
{{ include "agent-sandbox.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "agent-sandbox.apiServiceName" . }}-runtime-gateway-discovery
{{- end }}
{{- if .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "agent-sandbox.apiServiceName" . }}-leader-election
  namespace: {{ .Values.namespace }}
  labels:
{{ include "agent-sandbox.labels" . | indent 4 }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agent-sandbox.apiServiceName" . }}-leader-election
  namespace: {{ .Values.namespace }}
  labels:
{{ include "agent-sandbox.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "agent-sandbox.apiServiceName" . }}-leader-election
{{- end }}
