apiVersion: {{ .Values.api.service | quote }}
kind: Service
metadata:
  name: {{ include "agent-sandbox.apiServiceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "agent-sandbox.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    tier: {{ .Values.tier }}
    component: api-service
  ports:
    - name: http
      port: {{ .Values.service.apiService.port }}
      targetPort: http
      protocol: TCP
    - name: ssh
      port: {{ .Values.service.apiService.sshPort }}
      targetPort: ssh
      protocol: TCP
    - name: modal-grpc
      port: {{ .Values.service.apiService.modalGrpcPort }}
      targetPort: modal-grpc
      protocol: TCP
---
apiVersion: {{ .Values.api.service | quote }}
kind: Service
metadata:
  name: {{ include "agent-sandbox.runtimeGatewayName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "agent-sandbox.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    tier: {{ .Values.tier }}
    component: runtime-gateway
  ports:
    - name: http
      port: {{ .Values.service.runtimeGateway.httpPort }}
      targetPort: http
      protocol: TCP
---
apiVersion: {{ .Values.api.service | quote }}
kind: Service
metadata:
  name: {{ include "agent-sandbox.runtimeGatewayHeadlessName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "agent-sandbox.labels" . | indent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}
    tier: {{ .Values.tier }}
    component: runtime-gateway
  ports:
    - name: http
      port: {{ .Values.service.runtimeGateway.httpPort }}
      targetPort: http
      protocol: TCP
