{{- if .Values.secrets.create }}
apiVersion: {{ .Values.api.secret | quote }}
kind: Secret
metadata:
  name: {{ include "sndbx.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "sndbx.labels" . | indent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secrets.data.apiKey | quote }}
  INTERNAL_API_KEY: {{ .Values.secrets.data.internalApiKey | quote }}
  PORTAL_SESSION_SECRET: {{ .Values.secrets.data.portalSessionSecret | quote }}
  DATABASE_URL: {{ .Values.secrets.data.databaseUrl | quote }}
  DATABASE_TYPE: {{ .Values.secrets.data.databaseType | quote }}
  DATABASE_USERNAME: {{ .Values.secrets.data.databaseUsername | quote }}
  DATABASE_PASSWORD: {{ .Values.secrets.data.databasePassword | quote }}
  {{- if eq (include "sndbx.templateRegistryAuthRequired" .) "true" }}
  TEMPLATE_REGISTRY_USERNAME: {{ .Values.secrets.data.registryUsername | quote }}
  TEMPLATE_REGISTRY_PASSWORD: {{ .Values.secrets.data.registryPassword | quote }}
  {{- end }}
  {{- if eq (include "sndbx.imageBuildingAuthRequired" .) "true" }}
  {{ .Values.imageBuilding.bucketSecretKey }}: {{ .Values.secrets.data.imageBuildingS3Bucket | quote }}
  {{ .Values.imageBuilding.regionSecretKey }}: {{ .Values.secrets.data.imageBuildingS3Region | quote }}
  {{ .Values.imageBuilding.accessKeyIdSecretKey }}: {{ .Values.secrets.data.imageBuildingS3AccessKeyId | quote }}
  {{ .Values.imageBuilding.secretAccessKeySecretKey }}: {{ .Values.secrets.data.imageBuildingS3SecretAccessKey | quote }}
  {{ .Values.imageBuilding.sessionTokenSecretKey }}: {{ .Values.secrets.data.imageBuildingS3SessionToken | quote }}
  {{- end }}
{{- end }}
