{{- if .Values.secrets.create }}
apiVersion: {{ .Values.api.secret | quote }}
kind: Secret
metadata:
  name: {{ include "sndbx.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "sndbx.labels" . | indent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secrets.data.apiKey | quote }}
  INTERNAL_API_KEY: {{ .Values.secrets.data.internalApiKey | quote }}
  PORTAL_SESSION_SECRET: {{ .Values.secrets.data.portalSessionSecret | quote }}
  {{- if eq (include "sndbx.templateRegistryAuthRequired" .) "true" }}
  TEMPLATE_REGISTRY_USERNAME: {{ .Values.secrets.data.registryUsername | quote }}
  TEMPLATE_REGISTRY_PASSWORD: {{ .Values.secrets.data.registryPassword | quote }}
  {{- end }}
{{- end }}
