{{- if .Values.serviceAccount.create }}
apiVersion: {{ .Values.api.serviceaccount | quote }}
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "sndbx.labels" . | indent 4 }}
---
apiVersion: {{ .Values.api.role | quote }}
kind: Role
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "sndbx.labels" . | indent 4 }}
rules:
{{ toYaml .Values.rbac.rules | indent 2 }}
---
apiVersion: {{ .Values.api.rolebinding | quote }}
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "sndbx.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.serviceAccount.name }}
{{- end }}
