{{- if .Values.serviceAccount.create }}
apiVersion: {{ .Values.api.serviceaccount | quote }}
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "sndbx.labels" . | indent 4 }}
{{- end }}
